version: '3.8'

services:
    dynamodb-local:
        image: amazon/dynamodb-local:latest
        container_name: dynamodb-local
        ports:
            - '8000:8000'
        command: '-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data'
        volumes:
            - dynamodb-data:/home/dynamodblocal/data
        networks:
            - dentist-network

    dentist-api:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dentist-api
        ports:
            - '8080:8080'
        depends_on:
            - dynamodb-local
        environment:
            - DYNAMODB_ENDPOINT=http://dynamodb-local:8000
        networks:
            - dentist-network
        restart: unless-stopped

networks:
    dentist-network:
        driver: bridge

volumes:
    dynamodb-data:
